name: Blablador
options:
  bundleIdPrefix: de.fz-juelich
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "4Q84Z7RZ3Z"

targets:
  Blablador_iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Blablador
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.fz-juelich.blablador
        INFOPLIST_FILE: Blablador/Info.plist
        CODE_SIGN_ENTITLEMENTS: Blablador/Blablador.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Blablador
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        SDKROOT: iphoneos
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    entitlements:
      path: Blablador/Blablador.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)de.fz-juelich.blablador

  Blablador_macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Blablador
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.fz-juelich.blablador
        INFOPLIST_FILE: Blablador/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Blablador
        GENERATE_INFOPLIST_FILE: NO
        SDKROOT: macosx
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        DISABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "-"
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"