name: Blablador
options:
  bundleIdPrefix: de.fz-juelich
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "4Q84Z7RZ3Z"

targets:
  Blablador:
    type: application
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "17.0"
      macOS: "14.0"
    sources:
      - path: Blablador
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.fz-juelich.blablador
        INFOPLIST_FILE: Blablador/Info.plist
        CODE_SIGN_ENTITLEMENTS: Blablador/Blablador.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Blablador
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    entitlements:
      path: Blablador/Blablador.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)de.fz-juelich.blablador